Exposureapp 1781
corona-warn-app/cwa-app-android pull request #1048
Opened 2020-08-20 11:42 UTC by apopovsap

https://jira.itc.sap.com/browse/EXPOSUREAPP-1781#add-comment

2020-08-20 11:59 UTC, kolyaopahle requested changes
LGTM 👍 i made some small linting suggestions other than those im quite happy

2020-08-20 11:59 UTC, kolyaopahle commented on Corona-Warn-App/src/main/res/layout/include_16_years.xml
> +            type="de.rki.coronawarnapp.ui.viewmodel.TracingViewModel" />
Variable seems unused

2020-08-20 11:59 UTC, kolyaopahle commented on Corona-Warn-App/src/main/res/layout/include_16_years.xml
> +        <import type="de.rki.coronawarnapp.util.formatter.FormatterHelper" />
Formatters seem unused

2020-08-20 11:59 UTC, kolyaopahle commented on Corona-Warn-App/src/main/res/layout/include_16_years.xml
> +        <import type="de.rki.coronawarnapp.util.formatter.FormatterAccessibilityHelper" />
Formatters seem unused

2020-08-20 11:59 UTC, kolyaopahle commented on Corona-Warn-App/src/main/res/layout/include_16_years.xml
> +        <import type="android.view.View" />
View seems unused

2020-08-20 11:59 UTC, kolyaopahle commented on Corona-Warn-App/src/main/res/values/strings.xml
> +    <string name="sixteen_title_text">"App Nutzung ab 16 Jahren"</string>
Default strings should be empty

2020-08-20 11:59 UTC, kolyaopahle commented on Corona-Warn-App/src/main/res/values/strings.xml
> +    <string name="sixteen_description_text">"Die App richtet sich an Personen, die sich in Deutschland aufhalten und mindestens 16 Jahre alt sind."</string>
Default strings should be empty

2020-08-20 11:59 UTC, kolyaopahle commented on Corona-Warn-App/src/main/res/values/styles.xml
> +        <item name="android:textColor">@color/colorTextEmphasizedButton</item>
Is there a non button reference you could use?

2020-08-20 11:59 UTC, kolyaopahle commented on Corona-Warn-App/src/main/res/values/styles.xml
> +        <item name="android:textColor">@color/colorTextEmphasizedButton</item>
Is there a non button reference you could use?

2020-08-21 13:43 UTC, kolyaopahle approved these changes

2020-08-26 11:28 UTC, merged

2020-08-27 09:20 UTC, jakobmoellersap commented
https://jira.itc.sap.com/browse/EXPOSUREAPP-2092