Feature/interoperability target up de
corona-warn-app/cwa-app-android pull request #1102
Opened 2020-09-01 14:05 UTC by apopovsap

## Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [ ] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [ ] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) - Pull Requests that are not linked to an issue with you as an assignee will be closed, except for minor fixes for typos or grammar mistakes in *documentation or code comments*.
* [ ] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [ ] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)
* [ ] Make sure that your PR does not contain changes in text files, therefore the PR must not contain changes in values/strings/* and / or assets/* (see issue #332 for further information)
* [ ] Make sure that your PR does not contain compiled sources (already set by the default .gitignore) and / or binary files

## Description

2020-09-03 13:11 UTC, harambasicluka requested changes
I mainly looked at the codestyle, so please add comments if you are doing something different than anywhere else.

Some ids in the layout also should be renamed to fit the rest of the coding.

Also add the strings like described in the internal wiki.

Thanks <3

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/fragment_submission_target_de.xml
> +<?xml version="1.0" encoding="utf-8"?>
if yes use `german`/`germany` as de would be german :)

same for the other ids in this file

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/fragment_submission_target_de.xml
> +        android:id="@+id/submission_container"
I would suggest `submission_target_container`

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/fragment_submission_target_de.xml
> +            android:id="@+id/information_about_header"
`submission_target_header`

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/fragment_submission_target_de.xml
> +        <!--        </ScrollView>-->
unused comment?

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/include_target_de.xml
> +<?xml version="1.0" encoding="utf-8"?>
same as for the other file, also the ids would be affected

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/include_target_de.xml
> +            android:id="@+id/target_de_btn_apply"
please don't use `btn`, use `button`

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/include_target_de.xml
> +            style="@style/targetDeButtonNotPressed"
could be a more generic style, as buttons like this will be reused in the app, maybe also include would make sense

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/include_target_de.xml
> +            android:id="@+id/target_de_btn_reject"
also the id

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/include_target_de.xml
> +            style="@style/targetDeButtonNotPressed"
also the style

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/include_target_de.xml
> +            android:id="@+id/target_de_btn_verify"
same like before

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/colors.xml
> +    <!-- pressed button Interoperability -->
please remove this colors, as they are already defined

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/strings.xml
> +    <string name="target_de_text_subtitle">"Haben Sie sich in den letzten 14 Tagen außerhalb von Deutschland aufgehalten?"</string>
please change the ids to `submission_target_subtitle`, also the string should be empty. as it's in the default strings, e.g. `<string name="target_de_text_subtitle" />`

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/strings.xml
> +    <string name="target_de_text_subtitle">"Haben Sie sich in den letzten 14 Tagen außerhalb von Deutschland aufgehalten?"</string>
also relevant for all other strings added in this PR

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/strings.xml
> +    <string name="target_de_text_subtitle">"Haben Sie sich in den letzten 14 Tagen außerhalb von Deutschland aufgehalten?"</string>
And the strings should be also added in the german strings xml with the text

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/styles.xml
> +    <style name="targetDeButtonNotPressed">
like mentioned in the layout files: please create generic styles.

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTargetDe.kt
> +        binding.targetDe.targetDeVerify.setOnClickListener {
please add a comment to a block like this as this is different as the other `fun setButtonClickListener` functions we are using. maybe also think about extracting it to another functions.

2020-09-03 13:11 UTC, harambasicluka commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTargetDe.kt
> +            val constraintLayout = binding.targetDe.targetDeBtnApply
this also could be moved to an function

2020-09-07 13:43 UTC, harambasicluka requested changes

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-de/strings.xml
> +    <string name="target_text_subtitle">"Haben Sie sich in den letzten 14 Tagen außerhalb von Deutschland aufgehalten?"</string>
maybe also prefix with submission, e.g. `submission_target_subtitle`. Also add translation comments like the are used everywhere else.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-de/strings.xml
> +    <string name="target_text_subtitle">"Haben Sie sich in den letzten 14 Tagen außerhalb von Deutschland aufgehalten?"</string>
Also applys for the following strings.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-de/strings.xml
> +    <string name="target_text_next">"WEITER"</string>
don't write capslock, this should be handled via stylings.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-de/strings.xml
> +    <string name="target_verify_dialog_headline">"Headline"</string>
If the strings are still missing add `Lorem Ipsum`, so that everybody knows that it's a placeholder, you can reference to the `lorem_ipsum` string.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-de/strings.xml
> +    <string name="target_verify_dialog_body">"Are you sure?"</string>
If the strings are still missing add `Lorem Ipsum`, so that everybody knows that it's a placeholder, you can reference to the `lorem_ipsum` string.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-de/strings.xml
> +    <string name="target_verify_dialog_apply">"Apply"</string>
If the strings are still missing add `Lorem Ipsum`, so that everybody knows that it's a placeholder, you can reference to the `lorem_ipsum` string.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-de/strings.xml
> +    <string name="target_verify_dialog_cancel">"Back"</string>
If the strings are still missing add `Lorem Ipsum`, so that everybody knows that it's a placeholder, you can reference to the `lorem_ipsum` string.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-de/strings.xml
> +    <string name="submission_target_title">"Submission target > de title"</string>
If the strings are still missing add `Lorem Ipsum`, so that everybody knows that it's a placeholder, you can reference to the `lorem_ipsum` string.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/colors.xml
> +    <color name="colorTextGreenButtonPressed">#FFFFFF</color>
Sorry for not mentioning it before but for the color states we use: https://developer.android.com/guide/topics/resources/color-list-resource 

With that I don't think that this has to added here.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/colors.xml
> +    <color name="colorTextGreenButtonPressed">#FFFFFF</color>
And I can't see a green button in the screens.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/strings.xml
> +    <string name="target_text_subtitle" />
looks could only add the same comments like in the german file.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/colors.xml
> +    <color name="colorGreenButtonPressed">#5D6E80</color>
same as above.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/styles.xml
> +    <style name="greenButtonNotPressed">
why is this button called green if you use `colorSurface2`?

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/styles.xml
> +    <style name="greenButtonNotPressed">
states don't have to be handled over different stylings. If none of the existing color state lists have this behaviour create a new one and set the button to disabled instead only changing the color.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/include_target.xml
> +<?xml version="1.0" encoding="utf-8"?>
maybe call it `include_submission_target_selection` as target is really generic and I think this include is very specific.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTarget.kt
> +import kotlinx.android.synthetic.main.include_target.view.*
use viewbindings instead of ktlinx synthetic

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/layout/include_target.xml
> +        <androidx.constraintlayout.widget.ConstraintLayout
why do you use constraints with textViews wrapped in constraints instead of Buttons?

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTarget.kt
> +        if (constraintLayout.backgroundTintList === color) {
Please don't check for a color, that doesn't make sense, we want to check for a state.

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/styles.xml
> +    <style name="greenButtonPressed">
same here

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTarget.kt
> +    fun changeState(
I think that's not a proper solution, you should check for something like isSelcted. 

Good news @kolyaopahle has something in his branch, so I would wait for when his PR is included and than ask you to also use his include: https://github.com/corona-warn-app/cwa-app-android/compare/dev...feature/interoperability-country-screen#diff-5e94f42e06f6363bbdd344ac48d263fc

2020-09-07 13:43 UTC, harambasicluka commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/SubmissionTarget.kt
> +    fun changeState(
that somehow applies to most of this logic.

2020-09-07 14:08 UTC, harambasicluka commented
And please also add the Jira ticket to the title.

2020-09-17 13:21 UTC, BMItter commented
Due Storychange this PR is obsolet. Very low probability to come back ever.

2020-09-22 08:10 UTC, harambasicluka commented
Is replaced by https://github.com/corona-warn-app/cwa-app-android/pull/1145

2020-09-22 08:10 UTC, closed without merging