Text changes for existing user consent (EXPOSUREAPP-2751)
corona-warn-app/cwa-app-android pull request #1197
Opened 2020-09-21 12:19 UTC by chris-cwa

text changes for translation

2020-09-22 04:59 UTC, janetback requested changes
Hi, I don't think there should be a colon (:) here in this sentence, could you please check? Thanks.

"...stimmen Sie mit Antippen des Buttons: Risiko-Ermittlung aktivieren zu"

2020-09-24 06:52 UTC, chris-cwa commented
> Hi, I don't think there should be a colon (:) here in this sentence, could you please check? Thanks.
> 
> "...stimmen Sie mit Antippen des Buttons: Risiko-Ermittlung aktivieren zu"

Thank you!

2020-09-24 07:07 UTC, janetback approved these changes
UA approved

2020-09-24 12:14 UTC, harambasicluka approved these changes

2020-09-24 12:14 UTC, merged