Interoperability: New Note on Data Processing (EXPOSUREAPP-2742)
corona-warn-app/cwa-app-android pull request #1224
Opened 2020-09-24 09:14 UTC by AlexanderAlferov

Updated text for interoperability note.

2020-09-24 09:26 UTC, janetback approved these changes, later dismissed
UA reviewed

2020-09-24 09:34 UTC, MertSafter commented
@AlexanderAlferov I think the footer of the interoperability should only be used in the delta onboarding screen. For the normal onboarding screen there is already a data processing block I think. 
# Normal Onboarding
![image](https://user-images.githubusercontent.com/69803294/94127400-2b497400-fe59-11ea-8971-51a23ec132fb.png)

# Delta Onboarding
![image](https://user-images.githubusercontent.com/69803294/94127919-c80c1180-fe59-11ea-905b-8048cbb39269.png)

2020-09-24 11:20 UTC, MertSafter commented
@AlexanderAlferov I think it is not needed in include_onboarding.xml but also needed in fragment_onboarding_delta_interoperability. Could you also please check with UX/UI colleagues if it is needed in the normal onboarding scrren or is the already present privacy note in the onboarding screen enough

2020-09-24 11:40 UTC, jakobmoellersap requested changes, later dismissed
See Merts Comments

2020-09-25 14:16 UTC, MertSafter approved these changes
LGTM!

2020-09-28 11:10 UTC, janetback approved these changes
UA reviewed

2020-09-28 12:07 UTC, merged

2020-09-28 13:19 UTC, MikeMcC399 commented
Corona-Warn-App/src/main/res/values-de/strings.xml 
`interoperability_onboarding_delta_footerDescription` refers to iPhone, however this text is for an Android Smartphone not for an iPhone.

<string name="interoperability_onboarding_delta_footerDescription">Um zu erfahren, ob Sie Risiko-Begegnungen mit Nutzern der offiziellen Corona-Apps teilnehmender Länder* hatten und für Sie ein Infektionsrisiko besteht, müssen Sie nichts ändern. Es muss nur weiterhin die Funktion „Risiko-Ermittlung“ in der App aktiviert sein.\n\nBei aktivierter Kontaktaufzeichnung erzeugt Ihr iPhone kontinuierlich Zufalls-IDs und versendet diese per Bluetooth, die jetzt auch von Smartphones mit offizieller Corona-App der anderen teilnehmenden Länder in Ihrer Umgebung empfangen werden können. Umgekehrt empfängt Ihr **iPhone** die Zufalls-IDs der anderen Smartphones. Die eigenen und die von anderen Smartphones empfangenen Zufalls-IDs werden im COVID-19-Kontaktprotokoll aufgezeichnet und dort für 14 Tage gespeichert.\n\nFür die Risiko-Ermittlung lädt die App täglich oder auf Abfrage eine Liste mit den Zufalls-IDs aller Nutzer herunter, die diese über das europäische Serversystem geteilt haben, nachdem sie Corona-positiv getestet wurden. Diese Liste wird dann mit den im COVID-19-Kontaktprotokoll gespeicherten Zufalls-IDs verglichen.\n\nWenn dabei festgestellt wird, dass Sie eine Risiko-Begegnung hatten, werden Sie darüber von der App informiert. In diesem Fall erhält die App außerdem Zugriff auf weitere im COVID-19-Kontaktprotokoll Ihres **iPhone** gespeicherte Daten (Datum und Dauer sowie Bluetooth-Signalstärke des Kontakts).\n\nAus der Bluetooth-Signalstärke wird der räumliche Abstand zu dem anderen Nutzer abgeleitet (je stärker das Signal, desto geringer der Abstand). Diese Angaben werden von der App ausgewertet, um Ihr Gesundheitsrisiko abzuschätzen und Ihnen Empfehlungen für die nächsten Schritte zu geben. Diese Auswertung wird ausschließlich lokal auf Ihrem **iPhone** durchgeführt. Außer Ihnen erfährt niemand (auch nicht die Gesundheitsbehörden), ob Sie eine Risiko-Begegnung hatten und welches Risiko für Sie ermittelt wurde.\n\nDie Datenschutzhinweise der App (einschließlich Informationen zur Datenverarbeitung für die Risiko-Ermittlung) finden Sie unter dem Menüpunkt „Datenschutz“.</string>