Reduce code duplication (EXPOSUREAPP-2844)
corona-warn-app/cwa-app-android pull request #1286
Opened 2020-10-01 17:48 UTC by d4rken

## Description
Previously we had two `MainFragment` where the only different were the menu entries to the 2 test fragments we have. This also duplicated the `nav_graph.xml` in turn it caused by subtle issues and cost us time when switching between variants caused build errors until cache was cleared and where features were added to only one of the fragments.

This PR removes the extra `MainFragment`, introduces a `TestMenuFragment` as root for all test related screens, and hooks that into the main `nav_graph` via nested nav-graph inclusion. In `device` flavor builds, the nested nav-graph is a stub (empty) and the menu entry is hidden.

Future PRs can refactor the existing test fragments and move the mixed test code into their own Fragments to offer improved modularity and testing.

## How to test
* Review code etc.
* Deploy both `device` and `deviceForTesters` variant, the former should not have a test menu, while the later should have one.
* Navigate the test menu

2020-10-01 17:51 UTC, d4rken commented
@ UA I removed the test related texts from the strings.xml here. I don't see much sense in including test related strings in the translation process, using up valuable translation resources. IMHO test/debugging related strings should be in English and can be hardcoded.

2020-10-01 18:10 UTC, BMItter submitted a review, later dismissed
nice testmenu

2020-10-01 18:27 UTC, janetback requested changes
Hi, if this is appearing on UI, could you please add a ' ' (space) between Test an (Manual Test), i.e.
"Android API Test (Manual Test)"
Sorry for being pedantic.

2020-10-01 18:41 UTC, d4rken commented
@janetback These are strings only visible in the menus for testers, I can definitely fix the spacing, maybe we should even consider just removing the "test only" strings from the `strings.xml` translation files.

2020-10-01 18:49 UTC, janetback approved these changes, later dismissed
UA reviewed

2020-10-02 11:13 UTC, chris-cwa commented on Corona-Warn-App/src/deviceForTesters/java/de/rki/coronawarnapp/test/menu/ui/TestMenuFragmentViewModel.kt
> +        loadMenu()
please not in constructor - maybe create load method to call from <fragment>.onViewCreated()?

2020-10-02 11:14 UTC, chris-cwa commented on Corona-Warn-App/src/deviceForTesters/res/drawable/ic_bug.xml
> +</vector>
\n @ eof missing

2020-10-02 11:14 UTC, chris-cwa commented on Corona-Warn-App/src/deviceForTesters/res/drawable/ic_coffee.xml
> +</vector>
\n @ eof missing

2020-10-02 11:15 UTC, chris-cwa commented on Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_menu_adapter_item.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
\n @ eof missing

2020-10-02 11:15 UTC, chris-cwa commented on Corona-Warn-App/src/deviceForTesters/res/layout/fragment_test_menu.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
\n @ eof missing

2020-10-02 13:10 UTC, harambasicluka commented
> @janetback These are strings only visible in the menus for testers, I can definitely fix the spacing, maybe we should even consider just removing the "test only" strings from the `strings.xml` translation files.

I like the idea, if we do so and only remove the localdata strings we would have a clean string file!

2020-10-02 13:26 UTC, ralfgehrer approved these changes, later dismissed

2020-10-02 15:03 UTC, merged