Information on how to scan QR Code (EXPOSUREAPP-2581)
corona-warn-app/cwa-app-android pull request #1326
Opened 2020-10-06 10:22 UTC by Oliver-Zimmerman

New PR with 1.6 as base

## Description
Added a screen before the QR Code Scan screen in submission flow that explains how the QR Code scanning works.

- Created layout XML file
- Created Fragment 
- Created ViewModel
- Added required string files
- Updated navigation. 
- Added required illustrations

## Test
Begin the submission process, select QR option - you should be presented with the new screen. When next is clicked, you will be taken to the original QR scan screen. Back functionality should work appropriately.

2020-10-06 13:27 UTC, ralfgehrer commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeInfoFragment.kt
> +    private val binding: FragmentSubmissionQrCodeInfoBinding get() = _binding!!
Not a big fan of the "!!", especially since it could crash here.

2020-10-06 13:28 UTC, ralfgehrer commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeInfoFragment.kt
> +            if (it) {
it  could be given a better name

2020-10-06 13:29 UTC, ralfgehrer commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeInfoFragment.kt
> +            if (it) {
it could be given a better name

2020-10-06 13:41 UTC, ralfgehrer commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionQRCodeInfoFragmentViewModel.kt
> +    val navigateBack = SingleLiveEvent<Boolean>()
The overall navigation pattern looks odd to me for the following reasons:
- The boolean value will always be true (false will never be emitted)
- Sending an event to the VM and observing the same thing in the Fragment is somewhat duplicate. What's the advantage over calling the navigation in the fragment directly?
- If we go down that route, a navigate state/enum BACK and FORWARD and single Event to be observed and handled depending on the type might be more straight forward.
- tests are missing for the VM

2020-10-06 13:55 UTC, ralfgehrer commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeInfoFragment.kt
> +                (requireActivity() as MainActivity).goBack()
findNavController().popBackStack() is not doing the trick ?

2020-10-06 15:40 UTC, ralfgehrer submitted a review, later dismissed

2020-10-07 08:18 UTC, d4rken requested changes

2020-10-07 08:18 UTC, d4rken commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeInfoFragment.kt
> +    private val viewModel: SubmissionQRCodeInfoFragmentViewModel by viewModels()
Please inject in the viewmodel.

2020-10-07 08:18 UTC, d4rken commented on Corona-Warn-App/src/main/res/layout/fragment_submission_qr_code_info.xml
> +        <variable
Why do we need to add viewmodel here?

2020-10-07 08:18 UTC, d4rken commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/fragment/SubmissionQRCodeInfoFragment.kt
> +        binding.submissionCountrySelectViewModel = viewModel
I don't think we need this, there is no data-binding being used, right?

2020-10-07 13:22 UTC, ralfgehrer approved these changes

2020-10-09 06:56 UTC, SabineLoss approved these changes

2020-10-09 06:56 UTC, SabineLoss commented
UA reviewed

2020-10-12 12:18 UTC, kolyaopahle approved these changes
LGTM 👍

2020-10-12 12:28 UTC, ralfgehrer commented
@d4rken reviewed the request changes and is satisfied.

2020-10-12 12:36 UTC, merged