Risk change dialog pops up after being dismissed - fix (EXPOSUREAPP-3536)
corona-warn-app/cwa-app-android pull request #1518
Opened 2020-11-02 18:02 UTC by SamuraiKek

### Description

This PR fixes a bug where the LiveData from the VM wasn't getting updated anymore, causing a dialog to show up every time you traveled to another screen and then returned.
Issue was caused by LiveData being filtered and once it had a value, the filter was ignoring any other state the LiveData could be in.

2020-11-02 19:37 UTC, AlexanderAlferov approved these changes, later dismissed
Tested with steps in PR description.
Smoke tested.
lgtm

2020-11-02 19:49 UTC, BMItter submitted a review, later dismissed
Code looks clean to me and good to read :ok_hand:

2020-11-03 08:04 UTC, harambasicluka requested changes
lgtm, but I think the Project.xml shouldn't be part this PR.

2020-11-03 08:04 UTC, harambasicluka commented on .idea/codeStyles/Project.xml
> -<component name="ProjectCodeStyleConfiguration">
I think this shouldn't be part of your commit.

2020-11-03 09:03 UTC, harambasicluka approved these changes

2020-11-03 09:35 UTC, AlexanderAlferov approved these changes

2020-11-03 09:36 UTC, merged