Low Risk after update from 1.7.0 RC8 (in increased risk state) to 1.8.0 RC2 (EXPOSUREAPP-3988)
corona-warn-app/cwa-app-android pull request #1745
Opened 2020-11-27 11:52 UTC by chris-cwa

2020-11-27 14:42 UTC, d4rken requested changes

2020-11-27 14:42 UTC, d4rken commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/detectiontracker/TrackedExposureDetection.kt
> +    @SerializedName("enfVersion") val enfVersion: EnfVersion? = null
Please add unit tests for this, see `ExposureDetectionTrackerStorageTest`

2020-11-27 14:42 UTC, d4rken commented on Corona-Warn-App/src/test/java/de/rki/coronawarnapp/risk/RiskLevelTaskConfigTest.kt
> +    @MockK lateinit var exposureDetectionTracker: ExposureDetectionTracker
Please add unit tests for the new config behavior.

2020-11-30 12:51 UTC, chiljamgossow commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/task/TaskController.kt
>          // Procress all unprocessed finished tasks
another typo

2020-11-30 14:50 UTC, d4rken approved these changes, later dismissed

2020-11-30 14:52 UTC, chiljamgossow approved these changes, later dismissed

2020-11-30 15:22 UTC, d4rken approved these changes

2020-11-30 15:29 UTC, chiljamgossow approved these changes

2020-11-30 15:30 UTC, merged