Fix app crash because of wrong technical.html path (DEV)
corona-warn-app/cwa-app-android pull request #1883
Opened 2020-12-11 18:52 UTC by ralfgehrer

While testing #1882, I noticed that for some languages a non-existing `technical_en.html` is linked - which leads to an app crash :(

2020-12-11 18:58 UTC, d4rken requested changes

2020-12-11 18:58 UTC, d4rken commented on Corona-Warn-App/src/main/res/values-ro/strings.xml
> -    <string name="information_technical_html_path" translatable="false">"technical_en.html"</string>
technical**s** ?

2020-12-11 19:02 UTC, d4rken approved these changes

2020-12-14 07:13 UTC, chiljamgossow approved these changes

2020-12-14 07:57 UTC, merged