Wrong Item is used for Active Tracing Duration on High Risk Details (EXPOSUREAPP-4694)
corona-warn-app/cwa-app-android pull request #2168
Opened 2021-01-20 13:33 UTC by axelherbstreith

PR updates the icon for the Active Tracing Duration on the high Risk Details Card. See screenshot:

![image](https://user-images.githubusercontent.com/75120552/105181522-30c77a00-5b2c-11eb-93f2-65c26381567f.png)

2021-01-20 13:42 UTC, harambasicluka requested changes
The circle shouldn't be static it should use our custom view `CircleProgress`.

2021-01-20 15:55 UTC, axelherbstreith commented
> The circle shouldn't be static it should use our custom view `CircleProgress`.

@harambasicluka is changed 👍

2021-01-21 10:52 UTC, d4rken approved these changes
lgtm

2021-01-21 10:55 UTC, harambasicluka approved these changes

2021-01-21 11:14 UTC, merged