Added new strings.
corona-warn-app/cwa-app-android pull request #2464
Opened 2021-02-25 11:49 UTC by SamuraiKek

Strings for the new days since installation.

2021-03-01 10:23 UTC, harambasicluka requested changes
Please redo changes in all languages except german and default.

2021-03-01 10:23 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-bg/strings.xml
> +    <!-- XTXT: risk details - infection period logged information body, under 14 days -->
Please don't change the strings and comments, only change it in german and defaults. All other languages will be covered by the transition system. The string will just be unused until it's replaced.

2021-03-01 10:23 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-en/strings.xml
> +    <!-- XTXT: risk details - infection period logged information body, under 14 days -->
same as above

2021-03-01 10:23 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-pl/strings.xml
> +    <!-- XTXT: risk details - infection period logged information body, under 14 days -->
same as above

2021-03-01 10:23 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-ro/strings.xml
> +    <!-- XTXT: risk details - infection period logged information body, under 14 days -->
same as above

2021-03-01 10:23 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values-tr/strings.xml
> +    <!-- XTXT: risk details - infection period logged information body, under 14 days -->
same as above

2021-03-04 07:56 UTC, ralfgehrer approved these changes

2021-03-04 10:41 UTC, janetback approved these changes
UA reviewed

2021-03-04 12:33 UTC, harambasicluka approved these changes

2021-03-04 12:47 UTC, merged