Vaccination  (DEV)
corona-warn-app/cwa-app-android pull request #3015
Opened 2021-04-29 14:38 UTC by mtwalli

- Adds initial setup of vaccination details screen
- Creates gradient drawable to be used by others
- Fix test fragment DI 
- Creates common strings file for vaccination 
- Wire new graph to Main graph

You can see the new screen by going to vaccination test screen

2021-04-29 14:55 UTC, axelherbstreith submitted a review, later dismissed

2021-04-30 06:55 UTC, d4rken reviewed
Looks good. Small comments, no blockers.

2021-04-30 06:55 UTC, d4rken commented on Corona-Warn-App/src/deviceForTesters/res/navigation/test_nav_graph.xml
> +            android:name="certificateId"
`vaccinationCertificateId` ? Because we also have `ProofCertificate` which will probably also have an ID.

2021-04-30 06:55 UTC, d4rken commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/core/repository/VaccinationRepository.kt
> +    fun deleteVaccinationCertificate(certificateId: String) =
Should we make this `suspend`? Maybe the function above it too. UI Probably wants to block until the call is done?

2021-04-30 06:55 UTC, d4rken commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/vaccination/ui/details/VaccinationDetailsFragment.kt
> +                    R.drawable.vaccination_incomplete
Brackets or same line to improve reading this in commit diffs please, i.e.

```
if (it.isComplete) R.drawable.vaccination_compelete_gradient
else R.drawable.vaccination_incomplete
```

or  brackets.

2021-04-30 08:47 UTC, axelherbstreith approved these changes, later dismissed

2021-04-30 09:05 UTC, d4rken submitted a review, later dismissed
:+1:

2021-04-30 09:32 UTC, axelherbstreith approved these changes, later dismissed

2021-04-30 10:18 UTC, SabineLoss requested changes
Please use uppercase for "geboren"; rest is okay.

2021-04-30 10:24 UTC, SabineLoss approved these changes
UA reviewed

2021-04-30 10:25 UTC, axelherbstreith approved these changes

2021-04-30 10:30 UTC, d4rken approved these changes

2021-04-30 10:46 UTC, merged