Adjust test polling behavior 21 days  after registration (EXPOSUREAPP-6882)
corona-warn-app/cwa-app-android pull request #3016
Opened 2021-04-29 16:58 UTC by d4rken

* Map HTTP 400 errors to *_REDEEMED after 21 days (server has deleted data set).
* Stop test polling after 21 days if we are in a final state (*_REDEEMED).

* See ticket and related tech spec changes. 2.1.x hotfix target.
* Check test cases, right PCR/RAT results?
* Testable via mockserver and timetravel

2021-04-29 17:16 UTC, BMItter commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/coronatest/type/CoronaTestExtensions.kt
> +    return Duration(registeredAt, nowUTC).standardDays > 21
Personal preference, but i would use a default param here

2021-04-29 17:17 UTC, BMItter requested changes
NEVER! 
(sry, wrong PR 🥇 )

2021-04-29 17:17 UTC, BMItter approved these changes
lgtm!

2021-04-30 05:12 UTC, chiljamgossow approved these changes
Looks correct to me

2021-04-30 06:11 UTC, mlenkeit approved these changes
LGTM, verified for both PCR and RAT.

2021-04-30 06:17 UTC, merged