Updated Pending Result Screen (EXPOSUREAPP-6897)
corona-warn-app/cwa-app-android pull request #3053
Opened 2021-05-03 13:36 UTC by axelherbstreith

Adapted the Pending Test result screen for rapid antigen test according to Figma while leaving the screen for PCR tests as it currently is.

2021-05-06 07:32 UTC, LukasLechnerDev requested changes
2 optional suggestions. 

Why I request changes is that afaik we are not showing the RAT results in the diary yet (I think we will implement this in the next sprint (Version `2.4`)) So I think we need to remove the "Ihr Testergebnis wird dem Kontakt-Tagebuch hinzugefügt" Entry for now?

2021-05-06 07:32 UTC, LukasLechnerDev commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingViewModel.kt
> +    @Assisted val testType: CoronaTest.Type
You could access the type via `navArgs.testType` in the `ViewModel`. Then this property could stay private.

2021-05-06 07:32 UTC, LukasLechnerDev commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/testresult/pending/SubmissionTestResultPendingFragment.kt
> +        binding.apply {
Its a bit hard to figure out which view is displayed in which case 😅.

what about keeping it simple like

```
when (viewModel.testType) {
    CoronaTest.Type.PCR -> {
        testResultPendingStepsContactDiaryResult.isVisible = false
        testResultPendingStepsWaitingPcrResult.isVisible = true
        // and so on
    }
    CoronaTest.Type.RAPID_ANTIGEN -> {
        testResultPendingStepsContactDiaryResult.isVisible = true
        testResultPendingStepsWaitingPcrResult.isVisible = false
        // and so on
   }
}
```

2021-05-06 14:50 UTC, axelherbstreith commented
@LukasLechnerDev nice catch! The row is hidden now 👍

2021-05-07 06:49 UTC, LukasLechnerDev approved these changes, later dismissed
LGTM! Thanks for the fix :)

2021-05-07 10:23 UTC, harambasicluka commented on Corona-Warn-App/src/main/res/values/strings.xml
> +    <string name="submission_test_result_pending_steps_waiting_pcr_heading">"Your test result is not available yet."</string>
Just add the strings here, and do not change the old identifiers. With that you don't have to change other string files.

2021-05-07 10:54 UTC, InkenTownsend approved these changes
Correct according to https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6897. UA reviewed.

2021-05-07 13:25 UTC, chiljamgossow approved these changes
LGTM

2021-05-07 15:27 UTC, merged