Release strings for 2.3 (EXPOSUREAPP-6806)
corona-warn-app/cwa-app-android pull request #3207
Opened 2021-05-18 12:45 UTC by harambasicluka

☝️

2021-05-18 12:48 UTC, mtwalli submitted a review, later dismissed

2021-05-18 14:01 UTC, AlexanderAlferov approved these changes, later dismissed

2021-05-18 14:05 UTC, ChristinaTsigganos commented on Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
> +        <item>Sie können jetzt Ihre Impfungen in der App hinzufügen und jederzeit per QR-Code als Impfzertifikat vorweisen. 14 Tage nachdem Sie alle notwendigen Impfungen erhalten haben, können Sie d
Please change text to "Sie können jetzt Ihre Impfzertifikate in der App hinzufügen und per QR-Code vorweisen. 14 Tage nach der letzten Impfung zeigt die App den vollständigen Impfschutz an."

2021-05-18 14:05 UTC, ChristinaTsigganos requested changes
as soon as text changes are made, this PR is UA approved

2021-05-19 07:34 UTC, ChristinaTsigganos approved these changes
UA approved

2021-05-19 07:34 UTC, axelherbstreith approved these changes

2021-05-19 07:37 UTC, mtwalli approved these changes

2021-05-19 07:59 UTC, merged