Adapt Statistics Info screen (EXPOSUREAPP-7432)
corona-warn-app/cwa-app-android pull request #3472
Opened 2021-06-16 13:40 UTC by mtwalli

<img width="378" alt="Screenshot 2021-06-16 at 15 39 04" src="https://user-images.githubusercontent.com/25054729/122229498-17e3aa80-ceb9-11eb-99e2-0dedfc0f298e.png">
<img width="378" alt="Screenshot 2021-06-16 at 15 39 23" src="https://user-images.githubusercontent.com/25054729/122229504-19ad6e00-ceb9-11eb-9ab4-6967953a0d12.png">
<img width="378" alt="Screenshot 2021-06-16 at 15 39 37" src="https://user-images.githubusercontent.com/25054729/122229510-1a460480-ceb9-11eb-862d-a1487d1391d9.png">

2021-06-16 13:48 UTC, ChristinaTsigganos submitted a review, later dismissed
UA approved

2021-06-16 14:15 UTC, harambasicluka requested changes
Sorry, I have seen it too late. This part has to be removed as we won't add localized statistics in this release.
![image](https://user-images.githubusercontent.com/64483219/122235526-0ea90c80-cebe-11eb-99b7-56a5339aeba2.png)

2021-06-17 08:00 UTC, mtwalli commented
> Sorry, I have seen it too late. This part has to be removed as we won't add localized statistics in this release.

I hid it for now

2021-06-17 09:14 UTC, axelherbstreith approved these changes

2021-06-17 10:01 UTC, harambasicluka approved these changes

2021-06-17 10:40 UTC, merged