Info text and data privacy (EXPOSUREAPP-7650, EXPOSUREAPP-7619)
corona-warn-app/cwa-app-android pull request #3534
Opened 2021-06-23 15:57 UTC by harambasicluka

2021-06-23 16:39 UTC, axelherbstreith submitted a review, later dismissed

2021-06-24 06:06 UTC, jurajkusnier approved these changes, later dismissed

2021-06-24 07:01 UTC, NataliaLemmerth commented on Corona-Warn-App/src/main/assets/privacy_de.html
> +    COVID-19-Infektion. Die offizielle Bezeichnung lautet „EU Digitales COVID-Zertifikat“
```suggestion
    COVID-19-Infektion. Die offizielle Bezeichnung lautet „Digitales COVID-Zertifikat der EU“
```

2021-06-24 07:02 UTC, NataliaLemmerth requested changes
Please change the name to new official name: „Digitales COVID-Zertifikat der EU“.

2021-06-24 11:12 UTC, ChristinaTsigganos approved these changes
UA approved

2021-06-24 11:23 UTC, merged