Validation Rules Result Screen - valid (EXPOSUREAPP-8031)
corona-warn-app/cwa-app-android pull request #3593
Opened 2021-06-30 18:02 UTC by BMItter

This PR addresses EXPOSUREAPP-8031 (validation Result Screen - valid)
PR will be set to **DRAFT** because Button & Date - Wiring needed after Repo and Screens before this one are completed/merged (see EXPOSUREAPP-7738 for the flow)

Screenshot (scrolled down a little):
![screen](https://user-images.githubusercontent.com/46747780/124009543-08e31900-d9de-11eb-9ef6-b57e1f4f181a.png)

2021-07-01 06:37 UTC, ChristinaTsigganos commented on Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
> +    <string name="validation_rules_result_valid_result_title">Ihr Zertifikat ist im gewählten Reiseland gültig.</string>
Please change "Reiseland" to "Land", as displayed in Figma: https://www.figma.com/file/KuDEcMSREg3VhZRhC3FXTY/COVID19_Master_2.2?node-id=24596%3A21940

2021-07-01 06:39 UTC, ChristinaTsigganos commented on Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
> +    <string name="validation_rules_result_valid_result_title">Ihr Zertifikat ist im gewählten Reiseland gültig.</string>
same here, please change "Reiseland" to "Land".

2021-07-01 06:40 UTC, ChristinaTsigganos requested changes
Please adjust "Reiseland" to "Land", apart from that the texts are approved by UA

2021-07-02 14:37 UTC, vaubaehn commented
@harambasicluka @ChristinaTsigganos 

I'd suggest a small text enhancement for the 4th bullet point (even the text might also still be draft):

`Ob die im Zertifikat eingetragenen Daten richtig sind, wird `**von der Corona-Warn-App**` nicht geprüft.`

It's because the first three bullet points deal "with things outside the scope" of CWA. Especially the 3rd point is handling with "a verifier app". Hence, at least for me, the last bullet sounds like the verifier app won't check the contents of the certificate. Adding "von der Corona-Warn-App" clears it up imho, and hopefully _all_ users get it right then...

2021-07-07 11:41 UTC, harambasicluka commented
> @harambasicluka @ChristinaTsigganos
> 
> I'd suggest a small text enhancement for the 4th bullet point (even the text might also still be draft):
> 
> `Ob die im Zertifikat eingetragenen Daten richtig sind, wird `**von der Corona-Warn-App**` nicht geprüft.`
> 
> It's because the first three bullet points deal "with things outside the scope" of CWA. Especially the 3rd point is handling with "a verifier app". Hence, at least for me, the last bullet sounds like the verifier app won't check the contents of the certificate. Adding "von der Corona-Warn-App" clears it up imho, and hopefully _all_ users get it right then...
> 
> Edit: Or move the 4th bullet to the beginning as first bullet, and write as
> `Ob die im Zertifikat eingetragenen Daten richtig sind, wird `**hier**` nicht geprüft.` Then the coherence of the following three bullets fits also well.

Thanks @vaubaehn we are looking into this 👍

2021-07-08 08:49 UTC, ChristinaTsigganos commented
> @harambasicluka @ChristinaTsigganos
> 
> I'd suggest a small text enhancement for the 4th bullet point (even the text might also still be draft):
> 
> `Ob die im Zertifikat eingetragenen Daten richtig sind, wird `**von der Corona-Warn-App**` nicht geprüft.`
> 
> It's because the first three bullet points deal "with things outside the scope" of CWA. Especially the 3rd point is handling with "a verifier app". Hence, at least for me, the last bullet sounds like the verifier app won't check the contents of the certificate. Adding "von der Corona-Warn-App" clears it up imho, and hopefully _all_ users get it right then...
> 
> Edit: Or move the 4th bullet to the beginning as first bullet, and write as
> `Ob die im Zertifikat eingetragenen Daten richtig sind, wird `**hier**` nicht geprüft.` Then the coherence of the following three bullets fits also well.

Thanks a lot, @vaubaehn. We checked and decided to consider your first suggestion to add the information  "von der Corona-Warn-App" to the last bullet point. Thanks a lot for your valuable contribution to the CWA.

2021-07-08 11:07 UTC, BMItr commented
This PR will probably be closed and replaces by another due new Common-Model (new Base Branch).
Will clean it when its done.
No more review required here.

2021-07-09 13:59 UTC, BMItr commented
Follow UP: https://github.com/corona-warn-app/cwa-app-android/pull/3678

2021-07-09 13:59 UTC, closed without merging