Link to FAQ to find test centers (EXPOSUREAPP-8086)
corona-warn-app/cwa-app-android pull request #3688
Opened 2021-07-12 11:48 UTC by harambasicluka

TBD

2021-07-12 13:07 UTC, vaubaehn commented
You prefer opening FAQ over directly jumping to the map? As a fallback reason in case map service is interrupted/terminated? But TSI could provide a message on their site then. Like this it takes one click more effort to get to the map.

But nice to implement it in general 👍

2021-07-12 13:39 UTC, mtwalli approved these changes, later dismissed
Lgtm, tested on Android 6 emulator 😃

2021-07-12 14:04 UTC, harambasicluka commented
> You prefer opening FAQ over directly jumping to the map? As a fallback reason in case map service is interrupted/terminated? But TSI could provide a message on their site then. Like this it takes one click more effort to get to the map.
> 
> But nice to implement it in general 👍

@vaubaehn the FAQ entry contains multiple links and we want to be able to adjust the links without releasing a new app version :)

2021-07-12 14:14 UTC, vaubaehn commented
@harambasicluka 
Thanks, I simply forgot about the PCR tests, which are not necessarily included in the map. Also, the link to @Ein-Tim 's list is also worth to jump to FAQ :)

2021-07-12 14:53 UTC, harambasicluka commented
> @harambasicluka
> Thanks, I simply forgot about the PCR tests, which are not necessarily included in the map. Also, the link to @Ein-Tim 's list is also worth to jump to FAQ :)
> 
> Edit: why are you laughing about Android 6 emulator? It's important!! 😉

It was more like an internal joke, because it's my first implementation in a while :)

2021-07-12 21:20 UTC, DerVogel2020 reviewed
This will fix https://github.com/corona-warn-app/cwa-wishlist/issues/498

2021-07-12 21:20 UTC, DerVogel2020 commented on Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
> +    <string name="ag_homescreen_card_test_register_body">"Finden sie Teststellen in ihrer Umgebung und registrieren sie einen Test, um andere schneller warnen zu können, oder ihr digitales COVID-Test
Sie, Ihrer und Ihr müssten groß geschrieben werden.

2021-07-12 21:21 UTC, DerVogel2020 commented
Will this fix Internal Tracking ID: EXPOSUREAPP-7204?

2021-07-13 06:54 UTC, NataliaLemmerth commented on Corona-Warn-App/src/main/res/values-de/antigen_strings.xml
> +    <string name="ag_homescreen_card_test_register_body">"Finden sie Teststellen in ihrer Umgebung und registrieren sie einen Test, um andere schneller warnen zu können, oder ihr digitales COVID-Test
```suggestion
    <string name="ag_homescreen_card_test_register_body">"Finden Sie Teststellen in Ihrer Umgebung und registrieren Sie einen Test, um andere schneller warnen zu können, oder Ihr digitales COVID-Testzertifikat anzufordern."</string>
```

2021-07-13 06:57 UTC, NataliaLemmerth requested changes
Just these small text changes. Everything else is fine.

2021-07-13 07:36 UTC, BMItr approved these changes, later dismissed
nothing to complain 👌

2021-07-13 09:06 UTC, NataliaLemmerth approved these changes
UA approved

2021-07-13 09:12 UTC, harambasicluka commented
> Will this fix Internal Tracking ID: EXPOSUREAPP-7204?

@DerVogel2020 Yes! You can already check the URL: https://www.coronawarn.app/de/faq/#where_can_i_get_tested

2021-07-13 09:19 UTC, merged