Connect Validation Result List Items (EXPOSUREAPP-8329)
corona-warn-app/cwa-app-android pull request #3697
Opened 2021-07-13 06:35 UTC by axelherbstreith

WIP

2021-07-13 13:52 UTC, ChristinaTsigganos commented on Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
> +    <string name="validation_rule_technical_error_date_expired">"Das Zertifikat darf nicht abgelaufen sein."</string>
This message needs to be replaced by the new message "Das technische Ablaufdatum darf nicht überschritten sein.
" as described in Figma: https://www.figma.com/file/KuDEcMSREg3VhZRhC3FXTY/COVID19_Master_2.2?node-id=25537%3A21835

2021-07-13 13:54 UTC, ChristinaTsigganos commented on Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
> +    <string name="validation_rule_technical_error_date_expired">"Das Zertifikat darf nicht abgelaufen sein."</string>
same here please

2021-07-13 13:56 UTC, ChristinaTsigganos requested changes
Other than the text change to replace old by new message this PR is UA approved

2021-07-15 08:15 UTC, NataliaLemmerth commented on Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
> +    <string name="validation_rules_result_valid_result_title">"Ihr Zertifikat ist im gewählten Land gültig."</string>
```suggestion
    <string name="validation_rules_result_valid_result_title">"Ihr Zertifikat ist im gewählten Land gültig"</string>
```

2021-07-15 08:16 UTC, NataliaLemmerth commented on Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
> +    <string name="validation_rules_result_cannot_be_checked_result_title">"Ihr Zertifikat konnte nicht vollständig geprüft werden."</string>
```suggestion
    <string name="validation_rules_result_cannot_be_checked_result_title">"Ihr Zertifikat konnte nicht vollständig geprüft werden"</string>
```

2021-07-15 08:16 UTC, NataliaLemmerth commented on Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml
> +    <string name="validation_rules_result_not_valid_result_title">"Ihr Zertifikat ist im gewählten Land nicht gültig."</string>
```suggestion
    <string name="validation_rules_result_not_valid_result_title">"Ihr Zertifikat ist im gewählten Land nicht gültig"</string>
```

2021-07-15 08:17 UTC, NataliaLemmerth requested changes
Small text changes. Everything else is fine.

2021-07-15 08:24 UTC, NataliaLemmerth submitted a review, later dismissed
UA approved

2021-07-15 09:17 UTC, NataliaLemmerth approved these changes, later dismissed
UA approved

2021-07-15 10:31 UTC, NataliaLemmerth approved these changes, later dismissed
UA approved

2021-07-15 10:34 UTC, mtwalli submitted a review, later dismissed
Lgtm

2021-07-15 11:38 UTC, BMItr approved these changes
LGTM!
Basic Device Tests successful 👌 
![image](https://user-images.githubusercontent.com/46747780/125782045-f8066968-fdae-4d03-ba04-9fad4999d6cb.png)

2021-07-15 11:49 UTC, mtwalli approved these changes
LGTM

2021-07-15 11:54 UTC, merged