Increase ValueSet storage resilience (DEV)
corona-warn-app/cwa-app-android pull request #3750
Opened 2021-07-19 18:15 UTC by d4rken

Same treatment as #3742
* Mutex locking on storage
* Don't retwrite the initial dataset
* If we really fail to store the ValueSets (which uses the same storage mechanism as the certificates), then be loud and rethrow the exception.

2021-07-19 19:24 UTC, d4rken commented
Part of the hunt for #3549

2021-07-20 13:08 UTC, jurajkusnier approved these changes

2021-07-20 13:55 UTC, BMItr approved these changes
mtgl

2021-07-20 13:56 UTC, merged

2021-07-20 13:56 UTC, jurajkusnier requested changes
App crashed

2021-07-20 15:55:49.338 32095-32095/de.rki.coronawarnapp.test E/main: Uncaught exception!
2021-07-20 15:55:49.338 32095-32095/de.rki.coronawarnapp.test E/main: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
2021-07-20 15:55:49.338 32095-32095/de.rki.coronawarnapp.test E/main:  ViewHolder 1:LocalIncidenceCard{d6c104f position=2 id=2, oldPos=-1, pLpos:-1 not recyclable(1)} 
2021-07-20 15:55:49.338 32095-32095/de.rki.coronawarnapp.test E/main:  View Holder 2:LocalIncidenceCard{9a2701e position=2 id=2, oldPos=-1, pLpos:-1 not recyclable(1)} androidx.recyclerview.widget.RecyclerView{dcbe827 VFED..... ......ID 0,658-1080,1630 #7f0a06ef app:id/statistics_recyclerview}, adapter:de.rki.coronawarnapp.statistics.ui.homecards.StatisticsCardAdapter@5b7ead4, layout:de.rki.coronawarnapp.statistics.ui.homecards.StatisticsLayoutManager@cd3c47d, context:de.rki.coronawarnapp.ui.main.MainActivity@ca8b4f2