Recycle certificate confirm dialog (EXPOSUREAPP-9841)
corona-warn-app/cwa-app-android pull request #4208
Opened 2021-10-12 13:31 UTC by mtwalli

- Adjust DGC removal dialog

<img src="https://user-images.githubusercontent.com/25054729/136965445-323eebfb-afe5-4ac6-ac22-f9f3fe1e6466.png" width="300"/>

### Testing
1- Scan TC, VC, RC
2- Recycle them 
3- Scan them again
4- You should be asked on scanning that TC, VC, RC are in 🗑️ and you can restore them 
5- Check navigation to details screen 

## Ticket
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9841

2021-10-12 14:22 UTC, NataliaLemmerth commented on Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml
> +    <string name="recycle_bin_recycle_certificate_dialog_positive_button">"Zertifikat EntFernen"</string>
```suggestion
    <string name="recycle_bin_recycle_certificate_dialog_positive_button">"Zertifikat Entfernen"</string>
```

2021-10-12 14:23 UTC, NataliaLemmerth requested changes
Please take over these correction proposals. Everything else is fine.

2021-10-13 12:42 UTC, jurajkusnier approved these changes
LGTM

2021-10-13 12:53 UTC, BMItr approved these changes

2021-10-13 13:53 UTC, NataliaLemmerth approved these changes
UA approved

2021-10-13 14:00 UTC, merged