Update new features release 2.13 (EXPOSUREAPP-9811)
corona-warn-app/cwa-app-android pull request #4239
Opened 2021-10-18 15:10 UTC by chiljamgossow

new text on new feature screen

2021-10-18 15:43 UTC, marcauberer approved these changes, later dismissed
lgtm

2021-10-19 07:33 UTC, CV113 requested changes

2021-10-19 07:33 UTC, CV113 commented on Corona-Warn-App/src/main/res/values-de/release_info_strings.xml
> +        <item>Änderung des Links zu Häufige Fragen</item>
The word "häufige" must be written in lowercase

2021-10-19 08:00 UTC, marcauberer approved these changes

2021-10-19 08:02 UTC, CV113 approved these changes
UA approved

2021-10-19 09:01 UTC, mtwalli approved these changes

2021-10-19 09:01 UTC, merged