decorator
corona-warn-app/cwa-app-android pull request #4393
Opened 2021-11-16 11:41 UTC by chiljamgossow

2021-11-17 17:29 UTC, KathrinLuecke requested changes, later dismissed
Please correct dcc_ticketing_error_service_provider_error_no_name

2021-11-17 17:29 UTC, KathrinLuecke commented on Corona-Warn-App/src/main/res/values-de/dcc_ticketing_strings.xml
> +    <string name="dcc_ticketing_error_service_provider_error_no_name">Es trat ein Fehler bei der Verbindung mit dem Anbieter. Bitte kontaktieren Sie den Anbieter wenn das Problem weiterhin besteht.</
Please change "Es trat ein Fehler bei der Verbindung mit dem Anbieter." to "Es trat ein Fehler bei der Verbindung mit dem Anbieter auf." ("auf" is missing at the end).

2021-11-17 18:02 UTC, chiljamgossow commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/dccticketing/core/common/DccTicketingException.kt
> -
These are already covered in DccTicketingInvalidQrCodeException

2021-11-18 08:51 UTC, merged

2021-11-18 10:10 UTC, KathrinLuecke reviewed
UA approved