Statistics for boosters (EXPOSUREAPP-10765)
corona-warn-app/cwa-app-android pull request #4680
Opened 2022-01-11 12:39 UTC by SamuraiKek

Added a new statistics card that shows the number of people with boosters.

To test it, switch to `MOCK_CLOUD` and the card should be second to last. Don't mind the values, they're inflated from the mock server.

Also, make sure it works in night mode and that all the people on the cards are now wearing a mask in both light/dark mode.

2022-01-11 13:14 UTC, AlexanderAlferov requested changes
I think new text is missing in the Info Screen ℹ️ Kindly check the Figma 😄

2022-01-11 13:16 UTC, SamuraiKek commented
> I think new text is missing in the Info Screen ℹ️ Kindly check the Figma 😄

Thanks, I always forget about it 😄

2022-01-11 14:43 UTC, AlexanderAlferov approved these changes, later dismissed
LGTM 🚀

2022-01-12 08:38 UTC, CV113 submitted a review, later dismissed
UA approved

2022-01-12 11:49 UTC, jurajkusnier commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/StatsItem.kt
> +            Timber.w("PersonsVaccinatesWithBoostersStats is missing primary value")
PersonsVaccinatesWithBoostersStats > PersonsVaccinatedWithBoosterStats
typo?

2022-01-12 11:50 UTC, jurajkusnier reviewed
Could you double-check that Android texts are updated? There is a mismatch between iOS and Android design
<img width="818" alt="out" src="https://user-images.githubusercontent.com/2919625/149135176-94b76b30-2745-49a5-90c2-ea72ee972f66.png">

2022-01-13 08:42 UTC, SamuraiKek commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/StatsItem.kt
> +            Timber.w("PersonsVaccinatesWithBoostersStats is missing primary value")
Yes, good catch!

2022-01-13 11:40 UTC, SamuraiKek commented
> Could you double-check that Android texts are updated? There is a mismatch between iOS and Android design 

Turns out the iOS one is correct. I will update it.

2022-01-13 12:21 UTC, CV113 approved these changes
UA approved

2022-01-13 12:47 UTC, jurajkusnier approved these changes

2022-01-17 17:06 UTC, AlexanderAlferov approved these changes

2022-01-17 17:09 UTC, merged