Support new booster notation (EXPOSUREAPP-11272)
corona-warn-app/cwa-app-android pull request #4687
Opened 2022-01-14 11:40 UTC by jurajkusnier

### Testing
- scan as many DCC QR codes as you can and carefully watch which certificate has been selected as the certificate with the highest priority.
- focus on vaccination certificates where `doseNumber` > `totalSeriesOfDoses` or `v[0].dn is > than v[0].sd`
- you can generate such certificates using cli tool, eg:
```
cwa vc gen -o --pii 32 -s v.0.dt=2021-08-01T08:57:25Z -s v.0.dn=2 -s v.0.sd=1
```

### Jira Link
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11272

2022-01-14 13:06 UTC, vaubaehn requested changes

2022-01-14 13:06 UTC, vaubaehn commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
> + * v[0].dn is > 1 and v[0].mp equals EU/1/20/1525 (Johnson & Johnson) (booster vaccination), or
Hi @jurajkusnier ,
> v[0].dn is > 1 and v[0].mp equals EU/1/20/1525 (Johnson & Johnson) (booster vaccination)

For my understanding that won't work, when v[0] for both conditions is the _same_ DCC. I assume the array v[0] refers to the vaccination entry of _any_ DCC.
Think, a user was J&J-jabbed and enters that certificate into CWA first. Then v[0][1].dn is == 1 and v[0][1].mp is == EU/1/20/1525. Then user gets the booster with mRNA and enters the certificate as v[0][2]. Now v[0][2].dn is > 1and v[0][2].mp is different than EU/1/20/1525.
So, the check/filter would need to process 2 different certificates for that single result.

2022-01-14 13:21 UTC, vaubaehn commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificatesExtensions.kt
> + * v[0].dn is > 1 and v[0].mp equals EU/1/20/1525 (Johnson & Johnson) (booster vaccination), or
Sorry, please ignore my above comment.
I now understood that above condition refers to a booster _with_ J&J, not a booster _after_ J&J.
Then `v[0].dn is > than v[0].sd` will do the trick for the new EU notation and boosters _after_ J&J or recovery.
Sorry again

2022-01-17 07:47 UTC, SamuraiKek approved these changes
LGTM. Tested with the scenarios from #4343 and adjusted the 2/2 J&J vaccines to 2/1. Everything looks alright.

2022-01-18 13:42 UTC, chiljamgossow approved these changes
LGTM

2022-01-18 14:40 UTC, merged