Bind Dcc wallet info in person details screen (EXPOSUREAPP-11499)
corona-warn-app/cwa-app-android pull request #4745
Opened 2022-01-27 06:06 UTC by jurajkusnier

### Testing
- Add any certificate
- Open person details screen
- The person details screen contains mock data
- The "non-filled shield + checkmark" for VC is removed and not displayed anymore; was previously displayed during the 14-day waiting period (see Jira Story  https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11036)

### Jira Ticket
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11499

2022-01-27 11:09 UTC, mtwalli commented on Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
> +                    faqAnchor = "FAQ"
I think we should provide English too?

2022-01-30 22:24 UTC, jurajkusnier commented on Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/PersonDetailsFragmentTest.kt
> +                    faqAnchor = "FAQ"
updated

2022-01-31 12:27 UTC, AlexanderAlferov requested changes

2022-01-31 12:37 UTC, jurajkusnier commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ccl/dccwalletinfo/text/UrlResource.kt
> +        faqAnchor.isNullOrBlank() -> null
according to the documentation:
> if `faqAnchor` is set and not empty, a link to the FAQ with the link text shown in Figma and the URL derived from faqAnchor as per CCL > Resolving an FAQ Anchor to a URL ⎆. 
I don't see a use case where we should show FAQ links without an anchor.

2022-01-31 13:14 UTC, AlexanderAlferov approved these changes
Great job! Thanks for test menu.
As for FAQ: if changes required after clarification, I will handle it in my PR.

2022-01-31 13:53 UTC, SamuraiKek approved these changes
LGTM. Nice addition to the test menu ❤️

2022-01-31 13:54 UTC, merged