[UI] Family test selection and consent screen (EXPOSUREAPP-12316, EXPOSUREAPP-12317)
corona-warn-app/cwa-app-android pull request #4951
Opened 2022-03-17 17:09 UTC by AlexanderAlferov

### Whats new

Test type selection screen

![Screenshot 2022-03-17 at 18 12 56](https://user-images.githubusercontent.com/64849422/158854905-bb228014-7f5c-4991-b4bf-334f178a2e93.png)

##Family member consent consent

![Screenshot 2022-03-17 at 20 04 16](https://user-images.githubusercontent.com/64849422/158854930-08a42e74-2a66-4e8d-950a-1fba170b3b72.png)

### Story
[Story](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5895)
[Test type selection](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12316)
[Family member](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12317)

### How to test
1) scan any test
2) check test type selection fragment
3) press "Für andere" button
4) check family consent fragment
5) check that with empty name confirmation button is not enabled
6) type any name
7) check confirmation button is now enabled

### ToDo

- [x] Strings
- [x] New icons and illustration
- [x] Layouts
- [x] Wiring up

2022-03-17 17:42 UTC, Ein-Tim commented on Corona-Warn-App/src/main/res/values-de/family_tests_strings.xml
> +    <string name="family_consent_test_result">"Wenn Ihr Testergebnis negativ ist, können Sie dies in Form eines offiziellen COVID-Testzertifikats bestätigen lassen. Fordern Sie hierfür in den folgend
```suggestion
    <string name="family_consent_test_result">"Wenn das Testergebnis negativ ist, können Sie dies in Form eines offiziellen COVID-Testzertifikats bestätigen lassen. Fordern Sie hierfür in den folgenden Schritten das Testzertifikat an."</string>
```

2022-03-17 17:42 UTC, Ein-Tim commented on Corona-Warn-App/src/main/res/values-de/legal_strings.xml
> +    <string name="family_consent_legal_point_1" translatable="false">"<b>Die App ruft Ihr Testergebnis ab.</b>\nWenn Sie es sich später anders überlegen, können Sie den Test in der App löschen."</str
```suggestion
    <string name="family_consent_legal_point_1" translatable="false">"<b>Die App ruft das Testergebnis ab.</b>\nWenn Sie es sich später anders überlegen, können Sie den Test in der App löschen."</string>
```

2022-03-17 17:43 UTC, Ein-Tim requested changes
Bitte nicht "Ihr Testergebnis" nutzen, wenn es um das Testergebnis eines Familienmitgliedes geht. Das wird sonst verwirrend.

2022-03-17 23:36 UTC, AlexanderAlferov commented
> Bitte nicht "Ihr Testergebnis" nutzen, wenn es um das Testergebnis eines Familienmitgliedes geht. Das wird sonst verwirrend.

@KathrinLuecke FYI 👀

2022-03-21 18:29 UTC, Ein-Tim reviewed
Make it clearer what is meant here.

2022-03-21 18:29 UTC, Ein-Tim commented on Corona-Warn-App/src/main/res/values-de/family_tests_strings.xml
> +    <string name="family_consent_test_type">"Sie registrieren einien Test für ein Familienmitglied. Sollte es ihr eigener sein gehen Sie bitte zurück und wählen das aus. Nur so können Sie Ihre Begegn
```suggestion
    <string name="family_consent_test_type">"Sie registrieren einien Test für ein Familienmitglied. Sollte es ihr eigener sein gehen Sie bitte zurück und wählen das aus. Nur so können Sie Ihre Kontakte im Falle eines positiven Testergebnisses über die App warnen!"</string>
```

2022-03-22 07:56 UTC, KathrinLuecke commented
It looks like the screens for Android are not up-to-date in Figma. They are different from the iOS screens with regards to the wording. I will aks Anna-Maria to update them, then the texts here have to be adapted.

2022-03-22 08:00 UTC, KathrinLuecke commented
iOS:
![image](https://user-images.githubusercontent.com/91470863/159434301-e5c63f78-3838-4e5e-8732-3980b197f279.png)

2022-03-22 09:53 UTC, KathrinLuecke submitted a review, later dismissed
UA approved

2022-03-22 13:09 UTC, CV113 submitted a review, later dismissed
UA approved

2022-03-22 14:52 UTC, mtwalli commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionFragment.kt
> +}
Please rename `CoronaTestQRCode.CategoryType.OWN` to `CoronaTestQRCode.CategoryType.PERSONAL` for consistency?

2022-03-22 14:52 UTC, mtwalli commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionFragment.kt
> +                        coronaTestQrCode = navArgs.coronaTestQrCode
you need to create a copy of `coronaTestQrCode` and pass the right type based on user selection

2022-03-22 14:52 UTC, mtwalli commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionFragment.kt
> +                        coronaTestQrCode = navArgs.coronaTestQrCode
you need to create a copy of `coronaTestQrCode` and pass the right type based on user selection

2022-03-22 14:52 UTC, mtwalli commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionFragment.kt
> +                    .actionTestRegistrationSelectionFragmentToSubmissionConsentFragment(
that is not always the case , if there a test of the same type , you need to open the duplicate warning screen , see Figma

2022-03-22 14:52 UTC, mtwalli commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/consent/FamilyTestConsentViewModel.kt
> +            allowReplacement = true,
should be false , family test are allowing many tests we don't have replacement for them

2022-03-23 19:16 UTC, mtwalli reviewed
Great job ,slick UI

2022-03-23 19:16 UTC, mtwalli commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/familytest/ui/selection/TestRegistrationSelectionFragment.kt
> +        viewModel.routeToScreen.observe2(this) {
This screen stays in the navigation back stack even after the test is registered, I think when we navigate from here, it should be piped up from the stack

2022-03-24 13:25 UTC, mtwalli approved these changes, later dismissed
🚀🚀🚀🚀🚀

2022-03-24 14:57 UTC, SamuraiKek approved these changes
Let's go! 🚀

2022-03-24 15:14 UTC, merged