Update expired certificate details screen with new status subtitle.
corona-warn-app/cwa-app-android pull request #5151
Opened 2022-05-04 11:02 UTC by SamuraiKek

Small text change for the expired certificate details subtitle.

To test, generate an expiring certificate:

cwa vc gen --exp 5minutes -e mock-cloud -> go to certificate details and check the subtitle below the QR code. Compare with figma: https://www.figma.com/file/KuDEcMSREg3VhZRhC3FXTY/COVID19_Master_2.20?node-id=50171%3A36132

2022-05-04 13:27 UTC, KathrinLuecke requested changes

2022-05-04 13:27 UTC, KathrinLuecke commented on Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
> +    <string name="expired_certificate_info">"Das Ablaufdatum wurde überschritten. Bitte errneuern sie das Zertifikat. Sie können die Erneuerung bis maximal 3 Monate nach Ablauf über den Hinweis in Ih
```suggestion
    <string name="expired_certificate_info">"Das Ablaufdatum wurde überschritten. Bitte erneuern Sie das Zertifikat. Sie können die Erneuerung bis maximal 3 Monate nach Ablauf über den Hinweis in Ihrer Zertifikatsübersicht anfordern. "</string>
```

2022-05-05 08:46 UTC, chiljamgossow approved these changes

2022-05-05 11:05 UTC, BMItr approved these changes

2022-05-05 12:01 UTC, KathrinLuecke approved these changes
UA approved

2022-05-05 13:13 UTC, merged