All certificates PDF export info screen (EXPOSUREAPP-13261)
corona-warn-app/cwa-app-android pull request #5258
Opened 2022-06-03 09:43 UTC by SamuraiKek

Created a new info screen for exporting all certificates as pdf. 
To test, scan at least one certificate -> press the export button on the overview screen -> voila

2022-06-03 10:18 UTC, KathrinLuecke requested changes

2022-06-03 10:18 UTC, KathrinLuecke commented on Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml
> +    <string name="all_certs_pdf_export_info_point_pdf">Sie können in einem Schritt alle in Ihrer App gehaltenen Zertifikate in einem gemeinsamen PDF-Dokument speichern. Auf das PDF-Dokument haben zun
```suggestion
    <string name="all_certs_pdf_export_info_point_pdf">Sie können in einem Schritt alle in Ihrer App vorhandenen Zertifikate in einem gemeinsamen PDF-Dokument speichern. Auf das PDF-Dokument haben zunächst nur Sie Zugriff. Sie können im Anschluss entscheiden, ob Sie es auf Ihrem Smartphone speichern oder in andere Apps importieren möchten.</string>
```

2022-06-03 13:58 UTC, mtwalli approved these changes, later dismissed

2022-06-07 10:07 UTC, mtwalli approved these changes

2022-06-07 13:43 UTC, merged