Wallet info mask state (EXPOSUREAPP-13800)
corona-warn-app/cwa-app-android pull request #5486
Opened 2022-08-22 15:40 UTC by chiljamgossow

2022-08-22 17:50 UTC, MikeMcC399 commented on Corona-Warn-App/src/test/java/de/rki/coronawarnapp/ccl/dccwalletinfo/model/DccWalletInfoData.kt
> +        localizedText = mapOf("de" to "Aufgrund Ihre Zertifikate [...]"),
Ihre => Ihrer (Genitiv Plural)

2022-08-22 17:51 UTC, MikeMcC399 commented on Corona-Warn-App/src/test/resources/ccl/dcc_wallet_info_output_with_mask_state.json
> +        "de": "Aufgrund Ihre Zertifikate [...]"
Ihre => Ihrer

2022-08-22 17:52 UTC, MikeMcC399 requested changes
Suggest to check grammar of text (see in-line comments).

2022-08-23 07:39 UTC, mtwalli approved these changes
Lgtm

2022-08-23 07:51 UTC, merged