`Feature` SRS (EXPOSUREAPP-13454)
corona-warn-app/cwa-app-android pull request #5677
Opened 2022-11-02 13:32 UTC by mtwalli

👷🏼‍♂️ 🚧 
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13454

2022-11-02 14:02 UTC, Ein-Tim reviewed
One comment.

2022-11-02 14:02 UTC, Ein-Tim commented on Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/submission/viewmodel/SubmissionDispatcherViewModel.kt
> +            // proceed with SRS type  param
Double whitespace
```suggestion
            // proceed with SRS type param
```

2022-11-11 08:17 UTC, MikeMcC399 commented on Corona-Warn-App/src/main/res/values/srs_submission_strings.xml
> +    <string name="srs_submission_consent_disclaimer_subheadline_text">Bevor Sie andere warnen können, ist ihr Einverständnis erforderlich.</string>
"ihr Einverständnis" => "Ihr Einverständnis"

2022-11-11 08:22 UTC, MikeMcC399 requested changes
Typo - see in-line comment

2022-11-11 11:21 UTC, MikeMcC399 commented on Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
> +    <string name="srs_submission_consent_disclaimer_subheadline_text">Bevor Sie andere warnen können, ist ihr Einverständnis erforderlich.</string>
"ihr Einverständnis"?

2022-11-14 11:34 UTC, mtwalli commented
> Typo - see in-line comment

Fixed

2022-11-14 12:16 UTC, merged

2022-11-14 17:52 UTC, MikeMcC399 commented on Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
> +    <string name="srs_cancel_dialog_message">Sind Sie sich sicher, dass Sie den Warn-Vorgang abbrechen wollen?\n\Wenn Ihr Test positiv war, können Sie mit einer Warnung helfen, Infektionsketten zu un
Is `\n\Wenn` correct?
Previously it was `\n\nWenn` and it looks like one `\n` was intended to be deleted.

Same issue in file `values` directory as well.

2022-11-15 08:29 UTC, mtwalli commented on Corona-Warn-App/src/main/res/values-de/srs_submission_strings.xml
> +    <string name="srs_cancel_dialog_message">Sind Sie sich sicher, dass Sie den Warn-Vorgang abbrechen wollen?\n\Wenn Ihr Test positiv war, können Sie mit einer Warnung helfen, Infektionsketten zu un
https://github.com/corona-warn-app/cwa-app-android/pull/5709