Fix privacy notes (DEV)
corona-warn-app/cwa-app-android pull request #5907
Opened 2023-03-22 14:03 UTC by SamuraiKek

Addressing the comments from #5906 
Please have another look.

2023-03-22 14:48 UTC, MikeMcC399 commented on Corona-Warn-App/src/main/assets/privacy_de.html
In line 1
"Hinweise zur Beendigung der Verarbeitung personenbezogener"

is incomplete. I would expect "Daten" at the end.

2023-03-22 14:59 UTC, MikeMcC399 requested changes
Word missing at end of `h1` at top of document.

2023-03-22 15:28 UTC, SamuraiKek commented on Corona-Warn-App/src/main/assets/privacy_de.html
Thanks, I will update it.

2023-03-22 15:38 UTC, MikeMcC399 approved these changes
Changed heading (DE) looks fine now. 👍🏻

2023-03-23 07:27 UTC, OLVI5 approved these changes

2023-03-23 07:30 UTC, merged