Add ShareHelper
corona-warn-app/cwa-app-android pull request #85
Opened 2020-06-01 17:16 UTC by JSteegmueller

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [x] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger 
* [ ] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (if applicable)
* [ ] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [x] Make sure that your PR is not introducing _unncessary_ reformatting (e.g., introduced by on-save hooks in your IDE)
* [x] Check our [Contribution Guidelines](https://github.com/corona-warn-app/cwa-app-android/blob/master/CONTRIBUTING.md)

## Description

Resolves TODO "move to helper" in [MainShareFragment.kt](https://github.com/corona-warn-app/cwa-app-android/blob/90c49ae4ee75659cc96b603d0e0440e0dc0edcd3/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainShareFragment.kt#L53)

2020-06-01 21:43 UTC, marcauberer submitted a review, later dismissed

2020-06-02 07:46 UTC, harambasicluka requested changes
@JSteegmueller Please run `gradle quickBildWithFixes` locally :) 

So you can see directly the following error: https://678-268027139-gh.circle-artifacts.com/0/reports/ktlint/ktlintMainSourceSetCheck.txt

Please fix this, after that I'll approve and merge.

And thank you for the effort! 💯

2020-06-02 09:21 UTC, JSteegmueller commented
Fixed :)

2020-06-02 11:42 UTC, harambasicluka approved these changes
Thanks! :)

2020-06-02 11:42 UTC, merged